#!/bin/sh
#
# PROVIDE: imap4d
# REQUIRE: DAEMON
# BEFORE: mail
# KEYWORD: shutdown
#

. /etc/rc.subr

name="imap4d"
rcvar=imap4d_enable

: ${imap4d_enable="NO"}

command="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"

required_files="/usr/local/etc/mailutils.conf /usr/local/etc/mailutils/${name}"

extra_commands="configlint"
configlint_cmd="${name} --config-lint"

load_rc_config ${name}
run_rc_command "$1"
